version: '2.1'

services:
  easyrtc-server:
    image: easyrtc-server
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 8080:8080
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 server.js