# Example configuration:
# - velocity limits are around a 10% above the physical limits
# - acceleration limits are just low enough to avoid jerking

# Mandatory parameters
speed_lim_v: 0.25
speed_lim_w: 1.0

accel_lim_v: 0.5
accel_lim_w: 1.0

# Optional parameters
frequency: 20.0
decel_factor: 1.0

# Robot velocity feedback type:
#  0 - none
#  1 - odometry
#  2 - end robot commands
robot_feedback: 0

